# Montelibero Stellar Anchor <https://montelibero.org>
# https://github.com/stellar/stellar-protocol/tree/master/ecosystem

ACCOUNTS=[
"GDI4PH6R2B4JDTMONRJA3BV4L3IBMXHWFCQPP5VTDSD3EE2ZFZGQJZZO"
]

[DOCUMENTATION]
ORG_NAME="MTL ASSETS"
ORG_DBA="MTL ASSETS"
ORG_URL="https://assets.montelibero.org"
ORG_LOGO="https://montelibero.org/images/logo.png"
ORG_DESCRIPTION=""
ORG_GITHUB="montelibero-org"
ORG_OFFICIAL_EMAIL="montelibero.fspe@gmail.com"
ORG_SUPPORT_EMAIL="montelibero.fspe@gmail.com"

[[CURRENCIES]]
code="EHIN"
issuer="GDI4PH6R2B4JDTMONRJA3BV4L3IBMXHWFCQPP5VTDSD3EE2ZFZGQJZZO"
status="live"
display_decimals=7
anchor_asset_type="other"
is_asset_anchored=false
name="EHIN"
desc="EHIN - a personal token fixes the issuer's obligations to provide their service provider within 1 hour of working time for 1 token in the field of his professional competencies and capabilities."
image="https://assets.montelibero.org/images/logo/EHIN-GDI4PH6R2B4JDTMONRJA3BV4L3IBMXHWFCQPP5VTDSD3EE2ZFZGQJZZO.png"

[[CURRENCIES]]
code="NIRO"
issuer="GCOP3XDXTEHWPRXT3NSPPPR3RCHLLK6CUZI3S6RUWGEAKDD73IEU5H3E"
status="live"
display_decimals=7
anchor_asset_type="other"
is_asset_anchored=false
name="Niro Korb"
desc="A personal token fixes Victor Korb's readiness to provide services to its bearer within the limits of his professional competencies and capabilities at the rate of 1 hour for 1 token, and if refused for any reason, the obligation to redeem the token at a fixed price of 5 EURMTL."
image="https://assets.montelibero.org/images/logo/NIRO-GCOP3XDXTEHWPRXT3NSPPPR3RCHLLK6CUZI3S6RUWGEAKDD73IEU5H3E.png"

[[CURRENCIES]]
code="GPA"
issuer="GBGGX7QD3JCPFKOJTLBRAFU3SIME3WSNDXETWI63EDCORLBB6HIP2CRR"
status="live"
display_decimals=7
anchor_asset_type="other"
is_asset_anchored=false
name="GPA"
desc="GPA is a token of the same name company, which guarantees its owner monthly payments in EURMTL in the amount of 2% of the invested amount (at least 100 tokens) due to trading operations."
image="https://assets.montelibero.org/images/logo/GPA-GBGGX7QD3JCPFKOJTLBRAFU3SIME3WSNDXETWI63EDCORLBB6HIP2CRR.png"

[[CURRENCIES]]
code="GPACAR"
issuer="GBGGX7QD3JCPFKOJTLBRAFU3SIME3WSNDXETWI63EDCORLBB6HIP2CRR"
status="live"
display_decimals=7
anchor_asset_type="other"
is_asset_anchored=false
name="GPACAR"
desc="GPACAR is a token that fixes the obligations of the issuer in the field of acquisition and commercial management of car rental, with which you can invest through EURMTL or your own cars in order to extract rental income from them with the right to exchange tokens back for cars at the request of the depositor."
image="https://assets.montelibero.org/images/logo/GPACAR-GBGGX7QD3JCPFKOJTLBRAFU3SIME3WSNDXETWI63EDCORLBB6HIP2CRR.png"

[[CURRENCIES]]
code="MrxpInvest"
issuer="GDAJVYFMWNIKYM42M6NG3BLNYXC3GE3WMEZJWTSYH64JLZGWVJPTGGB7"
status="live"
display_decimals=7
anchor_asset_type="other"
is_asset_anchored=false
name="MrxpInvest"
desc="MrxpInvest quantitatively growing token with a fixed rate of 1 to 1 with EURMTL, fixing the obligations of the issuer in the field of work with a deposit in crypto trading and the obligation of the issuer within a month to return to the depositor the amount of funds requested for return with a proportional adjustment to MrxpCorrect on the distribution balance (where 100% of paper profit in token MrxpInves = 100% of the trader's real deposit, displayed in MrxpCorrect, through which commissions and drawdowns on the deposit are displayed on weekly terms)."
image="https://assets.montelibero.org/images/logo/MrxpInves-GDAJVYFMWNIKYM42M6NG3BLNYXC3GE3WMEZJWTSYH64JLZGWVJPTGGB7.png"

[[CURRENCIES]]
code="SwapCoin"
issuer="GCFSC5DDR4XGWFAOIWMGBXBY3BA7PTW4TGZ3RPFLCDFK67GCXWPUD2JS"
status="live"
display_decimals=7
anchor_asset_type="other"
is_asset_anchored=false
name="SwapCoin"
desc="SwapCoin a currency exchange bond which confirms the weekly obligation of the issuer to pay its holder the amount corresponding to inflation in Montenegro + 4% per annum  in EURMTL."
image="https://assets.montelibero.org/images/logo/SwapCoin-GCFSC5DDR4XGWFAOIWMGBXBY3BA7PTW4TGZ3RPFLCDFK67GCXWPUD2JS.png"

[[CURRENCIES]]
code="MTLDeja"
issuer="GCUA5D3Y2JL5MLVZFEHRBMKNOP3LGAIV5YDBGE5K2LNBRXIIXTOLAS5Z"
status="live"
display_decimals=7
anchor_asset_type="other"
is_asset_anchored=false
name="MTL Deja"
desc="crypto-shares guaranteeing equity participation in the ownership and management of all assets of the land plots 691, 692 and 694/2 in the district of Peƒçurice, Bar, Montenegro."
image="https://assets.montelibero.org/images/logo/MTLDeja-small-logo.png"

